### ISSUE TITLE
IllegalStateException: Expected a group when changing sliders in RichText demo

### ISSUE THREAD

**Issue by zach-klippenstein** [halilozercan/compose-richtext#7]
Seems to be triggered when `ListDemo` is followed by a `Heading`. Either of those on their own is fine.

Might be related to [this bug](https://issuetracker.google.com/issues/162226820), which is due to bad interaction between `remember` and default arguments.

Example stacktrace:
```
java.lang.IllegalStateException: Expected a group
    at androidx.compose.runtime.SlotTableKt.getAsGroup(SlotTable.kt:994)
    at androidx.compose.runtime.SlotTableKt.access$getAsGroup(Unknown Source:0)
    at androidx.compose.runtime.SlotReader.group$runtime_release(SlotTable.kt:46)
    at androidx.compose.runtime.Composer.nodeIndexOf(Composer.kt:1668)
    at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1544)
    at androidx.compose.runtime.Composer.skipToGroupEnd(Composer.kt:1784)
    at com.zachklipp.richtext.ui.DemoKt$RichTextDemo$1.invoke(Demo.kt:142)
    at com.zachklipp.richtext.ui.DemoKt$RichTextDemo$1.invoke(Unknown Source:13)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:153)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
    at com.zachklipp.richtext.ui.RichTextKt$RichText$1$1$1.invoke(RichText.kt:30)
    at com.zachklipp.richtext.ui.RichTextKt$RichText$1$1$1.invoke(Unknown Source:13)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:153)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
    at com.zachklipp.richtext.ui.RichTextScopeKt$WithStyle$1.invoke(RichTextScope.kt:35)
    at com.zachklipp.richtext.ui.RichTextScopeKt$WithStyle$1.invoke(Unknown Source:10)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
    at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:175)
    at com.zachklipp.richtext.ui.RichTextScopeKt.WithStyle(RichTextScope.kt:34)
    at com.zachklipp.richtext.ui.RichTextKt$RichText$1$1.invoke(RichText.kt:23)
    at com.zachklipp.richtext.ui.RichTextKt$RichText$1$1.invoke(Unknown Source:10)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:144)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
    at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
    at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1560)
    at androidx.compose.runtime.Composer.skipToGroupEnd(Composer.kt:1784)
    at com.zachklipp.richtext.ui.FormattedListKt.RestartListLevel(FormattedList.kt:156)
    at com.zachklipp.richtext.ui.RichTextKt.RichText(RichText.kt:21)
    at com.zachklipp.richtext.ui.DemoKt.RichTextDemo(Demo.kt:38)
    at com.zachklipp.richtext.sample.RichTextSampleKt$RichTextSample$1$1$1$2.invoke(RichTextSample.kt:58)
    at com.zachklipp.richtext.sample.RichTextSampleKt$RichTextSample$1$1$1$2.invoke(Unknown Source:13)
    at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:153)
    at androidx.compose.runtime.internal.ComposableLambda$invoke$1.invoke(ComposableLambda.kt:164)
    at androidx.compose.runtime.internal.ComposableLambda$invoke$1.invoke(Unknown Source:10)
    at androidx.compose.runtime.RecomposeScope.compose(Composer.kt:257)
    at androidx.compose.runtime.Composer.recomposeToGroupEnd(Composer.kt:1560)
    at androidx.compose.runtime.Composer.skipCurrentGroup(Composer.kt:1763)
    at androidx.compose.runtime.Composer.recompose(Composer.kt:1886)
    at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:259)
    at androidx.compose.runtime.Recomposer.access$performRecompose(Unknown Source:0)
    at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$2.invoke(Recomposer.kt:199)
    at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$2$2.invoke(Unknown Source:7)
    at androidx.compose.runtime.dispatch.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.kt:34)
    at androidx.compose.runtime.dispatch.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.kt:111)
    at androidx.compose.runtime.dispatch.AndroidUiDispatcher.access$performFrameDispatch(Unknown Source:0)
    at androidx.compose.runtime.dispatch.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.kt:71)
```

**Comment by zach-klippenstein** [comment]
Workaround seems to be making the `RichTextScope.FormattedList` that takes a vararg an inline function.
